# Generated by Django 4.2.16 on 2024-12-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
